{
  parserClass="org.intellij.sdk.language.parser.XuaParser"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="Xua"
  psiImplClassSuffix="Impl"
  psiPackage="org.intellij.sdk.language.psi"
  psiImplPackage="org.intellij.sdk.language.psi.impl"

  elementTypeHolderClass="org.intellij.sdk.language.psi.XuaTypes"
  elementTypeClass="org.intellij.sdk.language.psi.XuaElementType"
  tokenTypeClass="org.intellij.sdk.language.psi.XuaTokenType"

tokens = [
                       TYPE = "Type"
                   CRITERIA = "Criteria"
                     ENTITY = "Entity"
                     FIELDS = "Fields"
                 ADDITIONAL = "Additional"
                     METHOD = "Method"
                    REQUEST = "Request"
                   RESPONSE = "Response"
                       BODY = "Body"
                    LITERAL = "Literal"
                      MEANS = "Means"
                        PHP = "Php"
                 PARAMETERS = "Parameters"
                       TRUE = "TRUE"
                      FALSE = "FALSE"
                       NULL = "NULL"
                     Symbol = "regexp:[a-zA-Z_][a-zA-Z0-9_]*"
                    PhpCode = "regexp:(?:(?!\%\})(.|\s))*"
             StringConstant = "regexp:('([^'\\]|\\.)*'|\"([^\"\\]|\\\"|\\\'|\\)*\")"
               LanguageCode = 'regexp:af-ZA|sq-AL|ar-DZ|ar-BH|ar-EG|ar-IQ|ar-JO|ar-KW|ar-LB|ar-LY|ar-MA|ar-OM|ar-QA|ar-SA|ar-SY|ar-TN|ar-AE|ar-YE|hy-AM|Cy-az-AZ|Lt-az-AZ|eu-ES|be-BY|bg-BG|ca-ES|zh-CN|zh-HK|zh-MO|zh-SG|zh-TW|zh-CHS|zh-CHT|hr-HR|cs-CZ|da-DK|div-MV|nl-BE|nl-NL|en-AU|en-BZ|en-CA|en-CB|en-IE|en-JM|en-NZ|en-PH|en-ZA|en-TT|en-GB|en-US|en-ZW|et-EE|fo-FO|fa-IR|fi-FI|fr-BE|fr-CA|fr-FR|fr-LU|fr-MC|fr-CH|gl-ES|ka-GE|de-AT|de-DE|de-LI|de-LU|de-CH|el-GR|gu-IN|he-IL|hi-IN|hu-HU|is-IS|id-ID|it-IT|it-CH|ja-JP|kn-IN|kk-KZ|kok-IN|ko-KR|ky-KZ|lv-LV|lt-LT|mk-MK|ms-BN|ms-MY|mr-IN|mn-MN|nb-NO|nn-NO|pl-PL|pt-BR|pt-PT|pa-IN|ro-RO|ru-RU|sa-IN|Cy-sr-SP|Lt-sr-SP|sk-SK|sl-SI|es-AR|es-BO|es-CL|es-CO|es-CR|es-DO|es-EC|es-SV|es-GT|es-HN|es-MX|es-NI|es-PA|es-PY|es-PE|es-PR|es-ES|es-UY|es-VE|sw-KE|sv-FI|sv-SE|syr-SY|ta-IN|tt-RU|te-IN|th-TH|tr-TR|uk-UA|ur-PK|Cy-uz-UZ|Lt-uz-UZ|vi-VN'
                 NumberSign = "regexp:[-+]"
                BinConstant = "regexp:0b([01]+(\.[01]+)?|\.[01]+)"
                OctConstant = "regexp:0([01234567]+(\.[01234567]+)?|\.[01234567]+)"
                DecConstant = "regexp:([0123456789]+(\.[0123456789]+)?|\.[0123456789]+)"
                HexConstant = "regexp:0x([0123456789aAbBcCdDeEfF]+(\.[0123456789aAbBcCdDeEfF]+)?|\.[0123456789aAbBcCdDeEfF]+)"
]


  psiImplUtilClass="org.intellij.sdk.language.psi.impl.XuaPsiImplUtil"
}
                  XuaFile ::= TypeBlock
                            | EntityBlock
                            | MethodBlock
                            | LiteralBlock+
                            | ErrorBlock+
                            | ConstantBlock+
                TypeBlock ::= TYPE '(' ( Symbol ':' Expression ['=' Expression] ';')* ')' '{' CRITERIA ':' PhpBlock ';' '}'
              EntityBlock ::= ENTITY '{' FIELDS ':' ParametersBlock ';' ADDITIONAL ':' PhpBlock ';' '}'
              MethodBlock ::= METHOD '{' REQUEST ':' ParametersBlock ';' RESPONSE ':' ParametersBlock ';' [ BODY ':' PhpBlock ';'] '}'
             LiteralBlock ::= Symbol '=' LITERAL '{' ( LanguageCode ':' StringConstant ';' )* '}'
               ErrorBlock ::= Symbol MEANS LITERAL '::' Symbol
            ConstantBlock ::= Symbol '=' Expression;

               Expression ::= Symbol
                            | Symbol '(' (Symbol '=' Expression ';')* ')'
                            | '(' Expression ')'
                            | Expression '|' Expression
                            | Expression '&' Expression
                            | '!' Expression
                            | NumericConstant
                            | Expression '+' Expression
                            | Expression '-' Expression
                            | Expression '*' Expression
                            | Expression '/' Expression
                            | '+' Expression
                            | '-' Expression
                            | StringConstant
                            | ListConstant
                            | MapConstant
                            | ObjectConstant
                            | TRUE
                            | FALSE
                            | NULL
                PhpBlock  ::= PHP '{?' PhpCode '?}'
          ParametersBlock ::= PARAMETERS '{' (Symbol ':' Constant ['=' Constant] ';')* '}'
          NumericConstant ::= BinConstant
                            | OctConstant
                            | DecConstant
                            | HexConstant
             ListConstant ::= '[' (Constant ';')* ']'
